### ISSUE TITLE
Mfc

### ISSUE THREAD

**Issue by forsomefun2** [jrudess/streamdvr#106]
Where is MFC update yml updated to. 
There is no documentation for this feature. 

All I can tell is CB is being updated. MFC seems to update, but the configs stay the same. 
cb.yml= change
mfc.yml= no change

So where are all the model names being converted and added.

**Comment by jrudess** [comment]
The MFC uid is stored in mfc.yml, but there are three places this file can reside, and the first one that is found is used.  The search order is:

* $XDG_CONFIG_HOME/mfc.yml
* ~/.config/streamdvr/mfc.yml
* $cwd/config/mfc.yml

The updates might be going to one of the other directories.    I always use ~/.config/streamdvr for all my config files so that when I pull the git-repo for updates I never have to worry about conflicts (but you do have to check for updates and merge them back to your configs manually).

**Comment by forsomefun2** [comment]
the issue been fixed gitup didn't work they way I though. 

Fresh install fixes the issue.
