### ISSUE TITLE
streamdvr: command not found

### ISSUE THREAD

**Issue by e2489** [jrudess/streamdvr#127]
Forgive my ignorance, but the last time I installed this, things were much simpler. I have node.js installed, I have streamdvr copied into the folder, I run npm install and it installs. I run an Ubuntu terminal with Windows WSL installed, navigate to the folder and try to run 'streamdvr'. Then I get 'streamdvr: command not found'. What am I doing wrong?

**Comment by jrudess** [comment]
This is a linux-shell behavior thing.  For security reasons, by default the current directory is not part of $PATH, so to run an executable you need to type "./streamdvr".   Note that "node streamdvr" would also work.

When running just "streamdvr" it only looks in $PATH to find the executable.  Since the streamdvr directory isn't in $PATH you get the error "streamdvr: command not found".

**Comment by e2489** [comment]
If I enter './streamdvr' it says '/usr/bin/env: 'node' No such file or directory'
If I enter 'node streamdvr' it says 'Command 'node' not found, but can be installed with: sudo apt install nodejs', but I already have node installed and added to PATH.
