### ISSUE TITLE
Twitch.yml and others not updating

### ISSUE THREAD

**Issue by PurrSevere** [jrudess/streamdvr#130]
This has been working perfectly fine in v0.12.0, however, in v0.12.1, I've noticed that a few sites such as twitch, youtube and cb do not get updated when editing the site_updates.yml file.

The app is able to see the change and immediately starts recording the new user, but the site.yml file never gets updated to include them.

**Comment by SouthernBlackNerd** [comment]
So the issue seems to be in the updateStreamers function. 
```javascript
dirty |=  this.updateList(list[i], {add: options.add, pause: 0, isTemp: false, init: options.init});
```
updateList is async, so without an await, it doesn't wait to check all of the values before ending the functions.

```javascript
dirty |=  await this.updateList(list[i], {add: options.add, pause: 0, isTemp: false, init: options.init});
```
This line will fix that issue. You will also need to make updateStreamers async by adding the keyword async before it, so the whole function should look like this:
```javascript
async updateStreamers(list, options) {
    let dirty = false;

    for (let i = 0; i < list.length; i++) {
        dirty |=  await this.updateList(list[i], {add: options.add, pause: 0, isTemp: false, init: options.init});
    }

    return dirty;
}
```

**Comment by jrudess** [comment]
Good catch, and thanks for the debug.

**Comment by PurrSevere** [comment]
That fixed it, but It looks like underscore was accidentally removed in the latest commit. #131
