### ISSUE TITLE
username/password not working 

### ISSUE THREAD

**Issue by henao941** [jrudess/streamdvr#132]
The newer script for username/password isn't working for me, the previous versions before v0.12.1 were working fine, but this one isn't. 

Also, I want to request an enhancement. Could you add cache login credentials, for me it keeps needing to login every 10 minutes or so.

**Comment by jrudess** [comment]
Which site, and which m3u8fetch/recorder scripts are being used?

StreamDVR does not actually login to sites.  All it does is pass the login/pass on the command line to streamlink when it runs it.

**Comment by henao941** [comment]
The site is Pixiv. m3u8fetch: scripts/m3u8_streamlink.sh & recorder: scripts/record_streamlink.sh

So the login should work the same for streamdvr and streamlink, because only when I use streamdvr and the login function is when I receive notifications from Pixiv that there was a new login on my account.

**Comment by jrudess** [comment]
Yeah, it should be identical behavior to just using streamlink on its own.  The script code did change, so I'm sure that's where this got broken.  I don't have a pixiv account so testing is a bit tricky, but I make one if I don't see the issue on inspection.

**Comment by jrudess** [comment]
I made an account and on an initial test I'm not able to replicate any problem.   About the only thing I noticed was that I had to use:   "add pixiv user_dpem2758" to add "dpem2758" from the TUI interface instead of just "add pixiv dpem2758".    

The siteUrl argument in pixiv.yml can be changed to 'https://sketch.pixiv.net/@user_' to avoid having to prefix all names with 'user_'.   But the recording started up right away.    I may need to get you to post some sanitized logs that remove your username/password to debug this further, or can you send me the name of a pixiv account that you're having trouble with?

**Comment by jrudess** [comment]
Ah ignore the "user_" stuff.  that was actually the streamers name lol.

**Comment by jrudess** [comment]
I think I found the problem.  I've committed a fix to the master-branch.  Please test it out and let me know.

**Comment by henao941** [comment]
I've tested it and it seems to working fine now, thank you very much.
