### ISSUE TITLE
Terminating recording when stream offline detected (pandalive viewer limit)

### ISSUE THREAD

**Issue by challi1337** [jrudess/streamdvr#162]
On pandalive it can happen that when a recording is already running and a stream fills up (viewer limit) that on the next check if streams are live it detects it as offline and turns off the recording for it.

Is there a possible fix to turn off that behavior? On manual recording it just keeps recording through once you started it no matter the viewer limit.

**Comment by jrudess** [comment]
Fixed in d4f6ee9c

Apologies for the long delay -- haven't been actively using or coding streamdvr until recently.

You can add the following option to your 'pandalive.yml' config file to shut off this behavior:
```noTerminateOffline: true```

Keep in mind that there have been a lot of cases in the past where both yt-dlp and streamlink recording processes have gotten stuck even though the streamer went offline.  This is why streamdvr keeps checking whether the streamer is online, so that it can manually kill the recording process if it gets stuck.   When the above option is set to true that protection is disabled.
