### ISSUE TITLE
[Feature Request] Add support for streamlink proxy

### ISSUE THREAD

**Issue by PurrSevere** [jrudess/streamdvr#45]
It'd be awesome to be able to configure streamlink to use it's built-in proxy feature. 

More info here: https://streamlink.github.io/cli.html#proxy-support

**Comment by jrudess** [comment]
Looks pretty straightforward

**Comment by jrudess** [comment]
I've initially added support for https proxies but not http proxies.  This is because youtube-dl only takes a single proxy server input, and it's convenient to keep the streamlink/youtube-dl code shared.

Let me know if you run into instances where this causes issues.  It seems like most sites are using https, but I have not investigated them all, and don't have any proxy servers to test with.

**Comment by jrudess** [comment]
New config.yml options are:

proxyenable: true
proxyserver: socks5://127.0.0.1:1080

**Comment by PurrSevere** [comment]
So I finally had a chance to test this out today. It looks like it's only halfway working. It is able to detect that the model is online, but quickly switches to thinking the model is offline. It never start recording either.

Also, a model that isn't blocked in my state is able to record with the proxy enabled, however, it doesn't use the proxy to record.

Hope this helps figure out the issue.

![screen shot 2018-07-23 at 1 58 56 pm](https://user-images.githubusercontent.com/35707415/43102734-c94170ea-8e80-11e8-864e-130c8a3423ca.png)

**Comment by PurrSevere** [comment]
New issue that I just started noticing today. 
CB recordings work with the proxy enabled but not MFC.
