### ISSUE TITLE
Run at Reboot and Keep active at close

### ISSUE THREAD

**Issue by ghost** [jrudess/streamdvr#65]
I did this with my last recording program so I thought I would share it.  This is a way to keep the program running even when the headless machine window is not active 
My Operating System is a headless ubuntu system

This will
- Be a simple way to keep the script alive when closing  the ssh session
- Will allow for the session to start at reboot automatically

First you need byobu
- There are other programs but I find this one the easiest to use. It will probably come with your linux system, but it should be easy enough to install

You can make  a script to start a byobu session with the recorder in it with this code. I'd put the file in the root folder, for some reason I could never get it to work otherwise

```

#!/bin/sh
# byobu_launcher.sh ver 20170915122301 Copyright 2017 alexx, MIT Licence ver 1.0

byobu new-session -d -s $USER

# mongod
byobu new-window -t $USER:1 -n 'MFC'
byobu send-keys "/home/snickerpop/scripts/streamdvr.sh" C-m




# mongo
#byobu new-window -t $USER:1 -n 'mongo'
#byobu send-keys "/root/scripts/mfcr.sh" C-m

# Set default window as the dev split plane
#byobu select-window -t $USER:1

# Attach to the session you just created
# (flip between windows with alt -left and right)
#byobu attach-session -t $USER
exit

```

There is a second window name mongo that is completely commented out, but you can add in as many windows as you want to this.

Getting it to start at boot is easy enough
The folder and name for this file on ubuntu is /lib/systemd/system/byobu.service

```
[Unit]
Description=MFC Byobu
After=network.target

[Service]
ExecStart=/root/scripts/byobu.sh
User=root
Restart=always
RemainAfterExit=yes
KillMode=None

[Install]
 WantedBy=multi-user.target

```

Here are some commands to get it enable at boot, checking the status, and testing it before reboot
https://www.dynacont.net/documentation/linux/Useful_SystemD_commands/

make sure to chmod + x scripts

Note: It is easy enough to install rclone and from there you can auto export all your files at set intervals with a cronjob or jobber

**Comment by jrudess** [comment]
Thanks for posting your method. I have a rough example systemd unit file in the repo, but I have not played around with really defining a good reusable background service flow.

The flow I am currently using is that systemd restores my tmux session on login (tmux-resurrection plugin), and then I have tmux-ressurection configured to restore instances of 'node streamdvr.js' that were active when the session last ended.  One advantage to this flow is that tmux can detect and restart any number of instances in any number of terminals without having to add them to any configurations.   

But this is on login, and not boot, so it doesn't help if there is a power-cycle related restart.

**Comment by forsomefun2** [comment]
I'd say another way might with pm2

I I think  Byobu/Tmux have much better log management. It is kind of nice to be able to enter the byobu/tmux pane and to be able to quickly switch between applications. 

But PM2 is a bit easier to set up I think. 

I'm using pm2 start stream.js --kill-timeout 180000ms hopefully that will allow conversions to happen. Because I think the kill command leaves dead files.

**Comment by jrudess** [comment]
If I'm going to use a node-js process manager, I'm most likely to try final-pm rather than pm2.  

I'm not convinced that the node process manager solutions are the right approach to this particular package because of streamdvr's use-case, but I've been meaning to look into final-pm anyway.

**Comment by jrudess** [comment]
Improving the existing streamdvr.service for systemd and also making sure a good batch/daemon mode is working is something I want to do still.

**Comment by forsomefun2** [comment]
I ended up using pm2 because byobu had some issues

The issue is that if the system is forced to restart.  stream dvr has a bunch of abaddon files, that are never converted. 

I

**Comment by jrudess** [comment]
Sometime back I implemented code to find stale-files that were never converted when streamdvr gets started and auto-convert them.  

My method is still just to have systemd launch a user tmux process on boot, and then a tmux-plugin is setup to restart any streamdvr processes that were running in any panes when tmux was previously killed.

Since the methods that can be used for process management are many and mostly preferential, I can't think of anything else I could implement in StreamDVR to make process management easier.   If any ideas comes up, feel free to open a new issue.
