### ISSUE TITLE
streamlink vs ffmpeg performance + issue(s)

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#69]
Justed wanted your guys feedback on which one is better in terms of the quality of videos. Also wanted to ask if streamlink is like 100x times worse (slower) when it comes to start recording models if list is quite big?

**Comment by kuchenstrudel** [comment]
streamlink is better for me, because some model's recordings with ffmpeg are very choppy, which is something I was never able to fix.
That was the initial reason I suggested streamlink support to begin with.

That being said: streamlink starts way slower than ffmpeg and if you are not using MFCAuto, streamlink is used to make the lookups, which will be very slow, especially with a big list.

**Comment by Asynchr0nous** [comment]
I'm testing it out right now and its extremely slow. I only need to use it for chaturbate so don't need MFCAuto. I'm mainly using version 0.9.11 at the momemt (which used to get stuck for some reason but was fixed with node version 10.6.0) but currently running across new issue where it will only record few models here and there for like 5-10seconds

**Comment by Asynchr0nous** [comment]
just added random model and it took 3mins from add to actually start recording. Also just realised v0.9.11 has streamlink option too, do you know if it uses streamlink to fetch streaming url?

**Comment by jrudess** [comment]
Do you mean v0.9.1?

I'm not surprised that streamlink may be slower than the old scraping method, as I didn't run any performance comparisons. ;-)

But the reasons for code changes is to remove as much custom site knowledge from streamdvr for fetching m3u8 urls.  I want streamdvr to have no built in knowledge about how to build up an m3u8 URL and will let other programs deal with those details so that this program is purely about DVR capabilities.

Now if that other utility is also a node library that I make calls to directly, like MFCAuto, that is okay.  I only want code-base separation and not process separation.

**Comment by forsomefun2** [comment]
ffmpeg is still choppy for me as well. I'm testing a older version of streamlink
