### ISSUE TITLE
[Feature Request] Add Web Interface

### ISSUE THREAD

**Issue by PurrSevere** [jrudess/streamdvr#70]
This would be an awesome feature to have. I can help create the web  design side of things but have no idea how to make it talk with the app.

**Comment by jrudess** [comment]
Small update on this -- don't expect anything soonish.  But I've started to learn enough node apps for web sites, so this is likely to be implemented.

**Comment by PurrSevere** [comment]
Looking forward to it!

**Comment by jrudess** [comment]
I'm not spending as much time using StreamDVR anymore, and this feature is unlikely to ever get implemented by me.   The infrastructure to support something like this mostly exists, since the TUI code was setup to be isolated from the core DVR code (mostly).   So a WebUI class could be created still, and any pull requests would be welcome.
