### ISSUE TITLE
Way to add more plugins easily

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#90]
I think we need to discuss a simple way in which more plugins can be added to this script without heavily modifying it. I don't know what the best method would be but some kinda of common structure that all new plugins have to use will make it easier for you as well as others that want to contribute.

**Comment by jrudess** [comment]
As I separate out the m3u8 and recorder logic more from the core-functionality, I think this will naturally fall into place, or that is my goal.

When I started implementing support for streamlink and youtube-dl as m3u8 lookup tools, I wrote them as fully separate and self-contained classes.  When they were working, I realized that with some refactoring I could make 99% of the code common and not specific to either program, and so thats when basicsite.js got created.  

So the actual recorder-specific code in streamlink.js and youtubedl.js became very tiny files, and adding a new recorder should be as simple as giving the arguments for that program in some 'newrecorder.js' file.

In practice though, I expect every new recorder to require some amount of edits to basicsite.js because it currently contains some stdout/stderr processing logic to avoid printing false errors (most lookup programs print an error if the stream is offline, and that shouldn't be an error for streamdvr).   So I need to pull that code out and move the per-site custom parse strings back into streamlink.js/youtubedl.js.  That'll get this one step closer.

But I think the only way to get a really solid and reliable 'basicsite.js' that doesn't ever need editing when adding new m3u8 fetchers or recorders, is really just to start finding other utilities to use and adding them.  That will flush out all the 'basicsite.js' issues, or at least identify what has to be re-architected to make the core code generic.

**Comment by jrudess** [comment]
One idea, for flexibility is to define an interface for both m3u8 and recording to be a bash script.   Then anyone can write a bash script, and tell a site to use that for both of them.

**Comment by jrudess** [comment]
Actually, I'm really liking the idea of having all the ffmpeg/streamlink calls and arguments be stored in bash instead of a js array.  The array is a pain to edit anyway.

**Comment by Asynchr0nous** [comment]
Sounds good but would that have impact on performance?

**Comment by Asynchr0nous** [comment]
in regards to giving users ability to make their plugins work with this script, i was think what if you use a common format which you used for all you personal plugins in the past and currenly mfc:
```

const {Site}  = require("../core/site");
const _       = require("underscore");
const colors  = require("colors/safe");

class SiteName extends Site {
    constructor(name, tui) {
        super(name, tui);
        // set all common variables etc to work with rest of the script
        this.dirty = false;
    }


    async updateList(nm, add, isTemp) {
      // not sure if this was mfc specifc or not
    }

    async updateStreamers(list, add) {
      // not sure if this was mfc specifc or not
    }

    async checkStreamerState(uid) {

        let isStreaming = 0;
        let msg = colors.name(model.nm);

        if (!this.streamerList.has(uid)) {
            this.streamerList.set(uid, {uid: uid, nm: model.nm, site: this.padName, state: "Offline", filename: "", captureProcess: null, postProcess: 0});
        }

        const streamer = this.streamerList.get(uid);
        const prevState = streamer.state;

        if (online) {
            streamer.state = "Public Chat";
            msg += " is in public chat!";
            isStreaming = 1;
        } else if (grop) {
            streamer.state = "Group Show";
            msg += " is in a group show";
        } else if (private) {
            streamer.state = "Private";
            msg += " is in a private show.";
          }
        } else if (Away) {
            streamer.state = "Away";
            msg += " is away.";
        } else if (offline) {
            streamer.state = "Offline";
            msg += " has logged off.";
        }

        super.checkStreamerState(streamer, msg, isStreaming, prevState);

        if (isStreaming) {
            this.startCapture(this.setupCapture(streamer));
        }

        return true;
    }

    async getStreamers() {
        if (!super.getStreamers()) {
            return;
        }

        const queries = [];

        for (let i = 0; i < this.siteConfig.streamers.length; i++) {
            queries.push(this.checkStreamerState(this.siteConfig.streamers[i]));
        }

        // Only add a streamer from temp list if they are not
        // in the primary list.  Prevents duplicate recording.
        for (let i = 0; i < this.tempList.length; i++) {
            if (!_.contains(this.siteConfig.streamers, this.tempList[i])) {
                queries.push(this.checkStreamerState(this.tempList[i]));
            }
        }

        try {
            await Promise.all(queries);
        } catch (err) {
            this.errMsg(err.toString());
        }
    }

    setupCapture(model) {
        if (!super.setupCapture(model.uid)) {
            return {spawnArgs: "", filename: "", streamer: ""};
        }

        const filename = this.getFileName(model.nm);
        let url

        const spawnArgs = this.getCaptureArguments(url, filename, {params: params});

        return {spawnArgs: spawnArgs, filename: filename, streamer: model};
    }
}

exports.Plugin = SiteName;


```

**Comment by Asynchr0nous** [comment]
Most of the code above from mfc.js doesn;t need modifying and can be re-used. the main thing that needs changing is how you decide the model state

**Comment by jrudess** [comment]
basicsite.js is the common format code.   All plugins except MFC use it, and it's a single implementation that is working for multiple sites already.   MFC only has its own plugin only because it has to interact with the MFCAuto library and that necessitates some asynchronous handling differences.

With the new shell flow in top-of-tree, using youtube-dl to lookup m3u8 URLs is now abstracted to scripts/youtubedl.sh.  This makes basicsite.js even smaller.   

But if CB stops working to get m3u8 URLs with youtubedl.sh, but it does work with streamlink, then switching to streamlink just means editing cb.yml and changing ```m3u8fetch: streamlink.sh```

(streamlink.sh to be implemented)

**Comment by jrudess** [comment]
So next steps for this issue are to add the following options for a site.yml

```
m3u8fetch: scripts/streamlink_m3u8.sh
recorder: scripts/streamlink_record.sh
recorder: scripts/ffmpeg.sh
```

**Comment by jrudess** [comment]
CB, mixer and twitch all work with either m3u8_streamlink.sh or m3u8_youtubedl.sh now.   Pixiv only works with m3u8_streamlink.sh.    

However, I've left CB, mixer, and twitch to default with youtube-dl, since it is the larger project of the two.

**Comment by jrudess** [comment]
Almost all plugin files have been deleted and they are no longer necessary.  The current steps to add a new plugin for a site that works with streamlink or youtubedl is:

* update streamdvr.js to add a new table entry to fill in the plugin details.
* create plugin.yml and plugin_updates.yml

Other than that, no new js code should have to be written, unless the new site adds some new corner case (like pixiv did with its URL).

**Comment by Asynchr0nous** [comment]
Thanks alot. I will test it out throughly over next few days and see how things are. I plan on using few models for each site first before moving all my models from existing script. 

Few things I want to ask:
- In terms of performance would you say this is an improvement or not or the same? 

- I'm about to download the lastest commit now but i believe there may be a bug with debug outputs. I know that if all models are offline it will not print out anything but as long as one model is streaming/recording it will print `already recording` message. My question is, has this been disabled as once it says `model streaming recording started...`  no new messages get displayed unless a model is added/removed.

- Finally with this approach am I right to assume that the .sh files can be replaced with anything as long as only  m3u8 urls or errors are displayed by the script

**Comment by jrudess** [comment]
* I don't expect any major change in performance, except for the fixes made to serialize post-process conversions.

* Debug output should be fixed with latest commit, and it's going to be a lot more verbose.  I have a lot of new stuff added while I was debugging.  I may trim some of it back later.

* Correct, I would just copy the existing youtubedl script to a new name, and then start changing the command and figuring out what the error string it prints for 'offline' streams is (if any

).   I'm expecting to find that there may be other info I should pass into the scripts for other programs to work or to enable new features for existing ones.

**Comment by jrudess** [comment]
I've not tried to do any performance analysis to the old cb.js and the current basicsite.js flow.

**Comment by jrudess** [comment]
Pull requests are always welcome if you add any new script/m3u8 extractors.   

I still plan to implement per-site control of recorders instead of only global-control, but I'll track that elsewhere.
