### ISSUE TITLE
Help: "error 'script' not recognized as an internal or external command"

### ISSUE THREAD

**Issue by Ptibouc77** [jrudess/streamdvr#97]
I tried to use the latest version of streamdvr (i was still using a old one for a long time)
I updated node / steamlink and installed youtube-dl (i put it in my PATH)

But when i tried to run streamdvr i keep getting this error "error 'scripts' not recognized as an internal or external command"

I'm on Windows 10

**Comment by SearchAndDestroy** [comment]
I'm having the same problem
It's because the scripts are for Linux and not Windows but I managed to make it "work". It's super ugly and it outputs many errors e.g. when a streamer is offline.
1) edit all the sites files (cb.yml, mfc.yml, etc) and change the lines ```m3u8fetch: scripts/m3u8_streamlink.sh``` to ```m3u8fetch: scripts\m3u8_streamlink.cmd```
Idem for ````m3u8fetch: scripts/m3u8_youtubedl.sh```` to ```m3u8fetch: scripts\m3u8_youtube.cmd```
2) Create a file ```scripts\m3u8_streamlink.cmd``` and add ```@streamlink --stream-url %1 best```
3) Create a file ```scripts\m3u8_youtube.cmd``` and add ```@youtube-dl --simulate --get-url --skip-download %1```

You should be able to have the script running
I also changed cb to use streamlink.
I am sure @jrudess will come up with much better windows scripts :)

**Comment by jrudess** [comment]
I was wondering how much this would break windows flows.  I think it is possible to use node under windows with the bash scripts if you install WSL.  I.e. you can install the Ubuntu app on the microsoft store, which will give you a bash shell.  

If you run "node streamdvr.js" from that instead of a command prompt, then the scripts should all work.

**Comment by SearchAndDestroy** [comment]
I can try but I am running the script from a mapped drive on my NAS.
I will also need to install all the programs for Ubuntu.

**Comment by jrudess** [comment]
Yeah, its definitely a bit of setup to switch to a bash shell.  But it'll probably be the easiest way to keep using streamdvr going forward.

But, if anyone does spend the time to port the .sh files to .bat files for windows, I would accept that PR.

**Comment by SearchAndDestroy** [comment]
It's not so bad to run via MSL. I had to rem line 71 of streamdvr.js to avoid the above error and have the finished recordings moved but it's running great since a few hours :)

**Comment by jrudess** [comment]
@SearchAndDestroy Thanks for testing it out in WSL.  Line 71 is fixed.

**Comment by Hampster82** [comment]
Are Win7 and 8.1 users boned unless someone comes in and ports the scripts to something that's not bash?

I guess they could use an older version, until some site change breaks it.
It's a bit unfortunate.

Also I can't seem to get this working through WSL anyway, so I guess I'm boned too. 🤷‍♀

**Comment by jrudess** [comment]
You may be able to make a shortcut that runs the following to launch bash.  But typically a true bash program should accept -c to run commands on starting.

C:\Windows\System32\bash.exe -c "cd /path/to/streamdvr && node streamdvr.js"

**Comment by henao941** [comment]
I'm having some problems using WSL, was wondering if someone could help me.  
When I try to run.
```
node  streamdvr.js
```
I get this error.
```
Error: EACCES: permission denied, open '/home/user/streamdvr/streamdvr.js'
at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:351:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)
```
I tried using this instead 
```
sudo node  streamdvr.js
```
and it works fine for streams that use youtube-dl like Twitch, CB, and Mixer. But I'm having problems with FC2 and Pixiv streams. I've registered streamers in the config, but it doesn't seem to recognize that they are streaming and I don't get an error message. Also I sometimes get this message, is that normal?
```
ExperimentalWarning: The fs.promises API is experimental
```

**Comment by jrudess** [comment]
@henao941 this indicates a file permission issue and your normal user account doesn't appear to have read access (probably to config.yml itself).   This may have happened if you ran "sudo git clone https://github.com/jrudess/streamdvr"

To attempt to resolve it I would try this:
```
cd /home/user
sudo chown -R user streamdvr
chmod -R u+rw streamdvr
```

The fs.promises warning is normal and can be suppressed, see #88 

Both FC2 and Pixiv require extra setup steps related to streamlink to get working.   For FC2 you'll need to copy ```scripts/streamlink/fc2.py``` file to ```~/.config/streamlink/plugins/fc2.py```

On pixiv, I am not certain, but if it is not working, I would make sure to install the 'generic.py' plugin linked in the README the same way (copy it to ```~/.config/streamlink/plugins/```)

**Comment by Hampster82** [comment]
Well my WSL tests haven't been exactly positive. I need to put in some more streamers with different outputs, but so far it would seem like on mfc widescreen streams are capturing fine, but 800x600 streams are coming in super choppy, skipping frames like no one's business.

I guess no one else is having this problem since no one else has mentioned it. 😕

**Comment by jrudess** [comment]
@Hampster82 are you still having problems with choppy recordings underneath WSL?   Does it make any difference if you use ffmpeg or streamlink to record?

**Comment by Hampster82** [comment]
Yeah, I still seem to have problems.
I haven't tried streamlink at all, just ffmpeg.

I'll try to investigate a bit more.

**Comment by Hampster82** [comment]
Seems like using the record_streamlink bash script for MFC is a much better option in WSL, at least in my case. All manners of stream qualities and aspect ratios seem to be recording as well as the old pre-bash ffmpeg version.
Did notice one strange thing though, in the case of one MFC streamer the old pre-bash version just recorded one file while the latest version (as of 3 days ago) recorded a bunch of smaller files. Wasn't around to see what was happening, so hard to say what the cause was.

**Comment by Hampster82** [comment]
I couldn't really tell you. The normal Windows install is just a semi recent build from https://ffmpeg.zeranoe.com/builds/.
On WSL I used the install instructions from SearchAndDestroy few posts above, beyond that I have no idea.

**Comment by Hampster82** [comment]
Yeah, looks like 3.4.4 is the version that comes up when I execute it without arguments through bash. I'll do some tests with a newer one.

**Comment by jrudess** [comment]
Ah, great.  There's a strong change that is the issue.  FYI, you can check versions with "ffmpeg -version"

**Comment by Hampster82** [comment]
Yeah, it definitely appears that updating ffmpeg under WSL completely solved the choppy recording issue, and I haven't really seen any other issues either.

**Comment by jrudess** [comment]
Thanks for confirming!
